from django.urls import path
from . import api_views

urlpatterns = [
    path('auth/csrf/', api_views.api_csrf),
    path('auth/register/', api_views.api_register),
    path('auth/login/', api_views.api_login),
    path('auth/logout/', api_views.api_logout),
    path('auth/me/', api_views.api_me),
    path('profile/', api_views.api_profile),
    path('cvs/', api_views.api_cv_list_create),
    path('cvs/<int:pk>/', api_views.api_cv_detail),
    path('cvs/<int:pk>/duplicate/', api_views.api_cv_duplicate),
    path('cvs/<int:pk>/revisions/', api_views.api_cv_revisions),
    path('cvs/<int:pk>/revert/<int:rev_id>/', api_views.api_cv_revert),
    path('cvs/<int:pk>/export/pdf/', api_views.api_cv_export_pdf),
    path('cvs/<int:pk>/export/docx/', api_views.api_cv_export_docx),
    path('cvs/<int:pk>/share/', api_views.api_cv_share),
    path('cvs/<int:pk>/send-email/', api_views.api_cv_send_email),
    path('view/cv/<str:token>/', api_views.api_cv_public),
    path('letters/', api_views.api_letter_list_create),
    path('letters/<int:pk>/', api_views.api_letter_detail),
    path('letters/<int:pk>/duplicate/', api_views.api_letter_duplicate),
    path('letters/<int:pk>/revisions/', api_views.api_letter_revisions),
    path('letters/<int:pk>/revert/<int:rev_id>/', api_views.api_letter_revert),
    path('letters/<int:pk>/export/pdf/', api_views.api_letter_export_pdf),
    path('letters/<int:pk>/export/docx/', api_views.api_letter_export_docx),
    path('letters/<int:pk>/send-email/', api_views.api_letter_send_email),
    path('ai/enhance/', api_views.api_ai_enhance),
    path('ai/suggest-alternatives/', api_views.api_ai_suggest),
    path('ai/generate-letter-body/', api_views.api_ai_generate_letter),
    path('ai/write-email/', api_views.api_ai_write_email),
    path('ai/help/', api_views.api_ai_help),
    path('ai/tailor-cv/', api_views.api_ai_tailor_cv),
    path('ai/tailor-letter/', api_views.api_ai_tailor_letter),
    path('ai/ats/', api_views.api_ai_ats),
    path('applications/', api_views.api_applications),
    path('applications/<int:pk>/', api_views.api_application_detail),
    path('compose-email/', api_views.api_compose_email),
]
