# Generated by Django 4.2.7 on 2026-03-01 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(help_text='letter_type, title, recipient_*, company, body, sender_*')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.letter')),
            ],
            options={
                'verbose_name': 'Letter Revision',
                'verbose_name_plural': 'Letter Revisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(help_text='title, template, full_name, email, phone, location, summary, experience, education, skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.cv')),
            ],
            options={
                'verbose_name': 'CV Revision',
                'verbose_name_plural': 'CV Revisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
