# Generated by Django 4.2.7 on 2026-03-03 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_add_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='awards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='education_structured',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='experience_structured',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='projects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='share_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills_structured',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='cv',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cvrevision',
            name='snapshot',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('job_url', models.URLField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='documents.cv')),
                ('letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='documents.letter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-updated_at'],
            },
        ),
    ]
